# Setup
title: Xheni's Wiki
description: About security stuff and not only.
url: https://wiki.xheni.me
author:
  name: Xheni
  url: https://xheni.me
ga_id: todo
host: 10.211.55.4

sass:
  sass_dir: public/css
  style: compressed

exclude:
  - "*.sh"
  - "Dockerfile"
  - "Gemfile*"
  - "LICENSE"
  - "README.md"
  - "CNAME"

gems:
  - jekyll-sitemap
